### PR TITLE
[DPE-5565] Upgrade Kafka 3/stable release

### PR DESCRIPTION
**Pull request by deusebio**
## Charmed Apache Kafka bundle

New features and bug fixes in the Charmed Apache Kafka bundle:

### Features

* [DPE-2285] Refer to Charmhub space from GitHub (#200)
* [DPE-3333] Add integration test for broken tls (#188)
* [DPE-3721] chore: use tools-log4j.properties for run_bin_command (#201)
* [DPE-3735] Integration of custom alerting rules and dashboards (#180)
* [DPE-3780] Set workload version in install hook (#182)
* [DPE-3857] Test consistency between workload and metadata versions (#186)
* [DPE-3926] Enforce zookeeper client interface (#196)
* [DPE-3928] feat: secrets integration (#189)
* [DPE-5702] chore: Active Controllers alert set to == 0 (#252)
* [CSS-6503] Add OAuth support for non-charmed external clients (#168)
* [DPE-5757] Add `extra-listeners` config option (#269)

### Bug fixes

* [DPE-3880] Remove instance field from grafana dashboard (#191) 
* [DPE-3880] Remove all instances of $job variable in dashboard (#181)
* [DPE-3900] Remove APT references (#183)
* [DPE-3932] Fix illegal character on matrix channel (#187)
* [DPE-4133] Do not change permissions on existing folders when reusing storage (#195)
* [DPE-4362] fix: alive, restart and alive handling (#202)
* [DPE-5757] fix: ensure certs are refreshed on SANs DNS changes (#276)

### Other changes

* [MISC] Test on juju 3.4 (#190)
* [MISC] Update package dependencies
* [DPE-3588] Release documentation update  (#175)
* [MISC] CI improvements (#209)
* [DPE-3214] Release 3.6.1 (#179)
* [DPE-5565] Upgrade dataplatform libs to v38
* [discourse-gatekeeper] Migrate charm docs (#210, #203, #198, #194, #192)
* [DPE-3932] Update information in metadata.yaml

[DPE-2285]: https://warthogs.atlassian.net/browse/DPE-2285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3333]: https://warthogs.atlassian.net/browse/DPE-3333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3721]: https://warthogs.atlassian.net/browse/DPE-3721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3735]: https://warthogs.atlassian.net/browse/DPE-3735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3780]: https://warthogs.atlassian.net/browse/DPE-3780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3857]: https://warthogs.atlassian.net/browse/DPE-3857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3926]: https://warthogs.atlassian.net/browse/DPE-3926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3928]: https://warthogs.atlassian.net/browse/DPE-3928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-5702]: https://warthogs.atlassian.net/browse/DPE-5702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSS-6503]: https://warthogs.atlassian.net/browse/CSS-6503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-5757]: https://warthogs.atlassian.net/browse/DPE-5757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3880]: https://warthogs.atlassian.net/browse/DPE-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3880]: https://warthogs.atlassian.net/browse/DPE-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3900]: https://warthogs.atlassian.net/browse/DPE-3900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3932]: https://warthogs.atlassian.net/browse/DPE-3932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by marcoppenheimer** [comment]
@deusebio - are we good to close this now?

**Comment by deusebio** [comment]
Nope, we should merge this, such that we update 3/stable branch. I just want to have proper release notes (there is a PR about it) published on Discourse and GitHub

**Comment by deusebio** [comment]
Commit [c0a88cb](https://github.com/canonical/kafka-operator/pull/241/commits/c0a88cb4b373baecd9bc06d34ed2a85660b1e232) has been released to revision 194

**Comment by deusebio** [comment]
Commit [7948dfb](https://github.com/canonical/kafka-operator/pull/241/commits/7948dfbbfaaa53fccc88beaa90f80de1e70beaa9) has been released to revision 195 (and to 3/beta and 3/candidate channels)

**Pull request merged**
